### ISSUE TITLE
Hangs forever if a corner's been twisted

### ISSUE THREAD

**Issue by James-E-A** [pglass/cube#3]
If someone rotated a corner of the cube before giving it to me, perhaps as a prank, this isn't caught by the current codebase; it just hangs indefinitely.

```
>>> from rubik.cube import Cube
>>> from rubik.solve import Solver
>>> s = Solver(Cube('orwowgwywgbgrgrbobowyggbrrbybrgowoygryrbbgoobyoyrywyww'.upper()))
>>> s.solve()
^C…
```

For **other** non-solvable states, such as a flipped edge, the code [does catch these](https://github.com/pglass/cube/blob/e9ebb06af0270264c1577f7f97ba353d9ce4147e/rubik/solve.py#L95).

But when it comes to rotated corners, it just enters an infinite loop.

**Comment by pglass** [comment]
This is fixed in [0.0.2](https://pypi.org/project/rubik-cube/0.0.2/)
